version: '3.8'

services:
  db:
    image: mayankjonwal02/iitj_face_verification_backend-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: UserDatabase
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_network

  frontalface:
    image: mayankjonwal02/iitj_face_verification_backend-frontalface
    ports:
      - "8001:8001"
    networks:
      - backend_network

  web:
    image: mayankjonwal02/iitj_face_verification_backend-web
    command: ["sh", "-c", "python manage.py migrate && gunicorn libraryproject.wsgi:application --bind 0.0.0.0:8000 --timeout 120"]
    volumes:
      - ./libraryproject:/app
    depends_on:
      - db
      - frontalface
      
    environment:
      - DB_HOST=db
      - DB_NAME=UserDatabase
      - DB_USER=root
      - DB_PASS=
    networks:
      - backend_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8003:8003"
    depends_on:
      - web
    networks:
      - backend_network

volumes:
  mysql_data:

networks:
  backend_network:
    driver: bridge
